"""FastAPI REST routes for the Social Media Helper backend.

Endpoints:
  GET  /health               – liveness check
  GET  /api/feed             – aggregated feed (deduped, categorised, summarised)
  GET  /api/feed/categories  – list of available categories
  GET  /api/digest           – LLM-generated daily digest (markdown)
"""

from __future__ import annotations

import asyncio
import logging
import time
from typing import Any

from fastapi import APIRouter, HTTPException, Query

from mcp_server.config import settings
from mcp_server.feeds.hackernews import HackerNewsFeedReader
from mcp_server.feeds.onet import get_onet_readers
from mcp_server.feeds.rss_reader import RssFeedReader
from mcp_server.processing.categorizer import categorise_items
from mcp_server.processing.deduplicator import deduplicate
from mcp_server.processing.summarizer import generate_daily_digest, summarise_items

logger = logging.getLogger(__name__)
router = APIRouter()

# ---------------------------------------------------------------------------
# Simple in-memory cache
# ---------------------------------------------------------------------------
_cache: dict[str, tuple[float, Any]] = {}


def _get_cached(key: str, ttl: int) -> Any | None:
    entry = _cache.get(key)
    if entry and (time.monotonic() - entry[0]) < ttl:
        return entry[1]
    return None


def _set_cached(key: str, value: Any) -> None:
    _cache[key] = (time.monotonic(), value)


# ---------------------------------------------------------------------------
# Feed assembly
# ---------------------------------------------------------------------------

async def _fetch_all_items():
    readers = [
        HackerNewsFeedReader(top_n=settings.hackernews_top_n),
        *get_onet_readers(),
        *[RssFeedReader(url) for url in settings.rss_feeds],
    ]
    results = await asyncio.gather(*[r.fetch() for r in readers], return_exceptions=True)
    items = []
    for r in results:
        if isinstance(r, Exception):
            logger.warning("Feed fetch error: %s", r)
        else:
            items.extend(r)
    return items


async def _get_processed_feed():
    cached = _get_cached("feed", settings.cache_ttl_seconds)
    if cached is not None:
        return cached

    raw = await _fetch_all_items()
    categorised = categorise_items(raw)
    deduped = deduplicate(categorised, threshold=settings.dedup_similarity_threshold)
    # Sort by score desc, then by date desc
    deduped.sort(key=lambda x: (x.score, x.published_at), reverse=True)
    summarised = await summarise_items(
        deduped[: settings.summary_max_items],
        openai_api_key=settings.openai_api_key,
        openai_model=settings.openai_model,
        openai_base_url=settings.openai_base_url,
    )
    _set_cached("feed", summarised)
    return summarised


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@router.get("/health")
async def health():
    return {"status": "ok"}


@router.get("/api/feed")
async def get_feed(
    category: str | None = Query(default=None, description="Filter by category"),
    limit: int = Query(default=30, ge=1, le=100),
    offset: int = Query(default=0, ge=0),
):
    """Return the processed feed as a list of items."""
    try:
        items = await _get_processed_feed()
    except Exception as exc:
        logger.exception("Feed processing error")
        raise HTTPException(status_code=500, detail=str(exc)) from exc

    if category:
        items = [i for i in items if i.category == category]

    total = len(items)
    page = items[offset : offset + limit]
    return {
        "total": total,
        "offset": offset,
        "limit": limit,
        "items": [i.to_dict() for i in page],
    }


@router.get("/api/feed/categories")
async def get_categories():
    """Return all categories present in the current feed."""
    try:
        items = await _get_processed_feed()
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc
    categories = sorted({i.category for i in items})
    return {"categories": categories}


@router.get("/api/digest")
async def get_digest():
    """Return a markdown daily digest generated by the LLM."""
    cached = _get_cached("digest", settings.cache_ttl_seconds)
    if cached:
        return {"digest": cached}
    try:
        items = await _get_processed_feed()
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc

    digest = await generate_daily_digest(
        items,
        openai_api_key=settings.openai_api_key,
        openai_model=settings.openai_model,
        openai_base_url=settings.openai_base_url,
    )
    _set_cached("digest", digest)
    return {"digest": digest}
